# Generated by Django 2.1.1 on 2018-09-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Location', models.CharField(max_length=60)),
                ('Age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
